# Generated by amazon-chime-sdk-rails
class Api::MeetingAttendeesController < ::MeetingAttendeesController
  before_action :authenticate_user!
  include DeviseTokenAuth::Concerns::SetUserByToken
  before_action :set_room
  before_action :check_membership

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:room_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def check_membership
    unless @room.member?(current_user)
      message = 'Unauthorized: you are not a member of this private room.'
      respond_to do |format|
        format.html { redirect_to @room, notice: message }
        format.json { render json: { room: @room, notice: message }, status: :forbidden }
      end
    end
  end
end