language: ruby

branches:
  except:
    - images

rvm:
  - 2.7.3

gemfile:
  - gemfiles/Gemfile.rails-5.0
  - gemfiles/Gemfile.rails-5.1
  - gemfiles/Gemfile.rails-5.2
  - gemfiles/Gemfile.rails-6.0
  - gemfiles/Gemfile.rails-6.1

matrix:
  include:
    - rvm: ruby-head
      gemfile: Gemfile
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

sudo: false

cache: bundler

before_install:
  - gem install bundler
  - nvm install node

install:
  - bundle install

before_script:
  - cd spec/rails_app
  - yarn --check-files
  - bundle exec rails webpacker:compile
  - bundle exec rails g chime_sdk:js
  - cd -

script:
  - bundle exec rspec

notifications:
  email: true
