Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name for the service.
  Name:
    Type: String
    Description: The name of the service.

Resources:
  # https://docs.aws.amazon.com/chime-sdk/latest/ag/security_iam_id-based-policy-examples-chime-sdk.html
  # https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_Operations_Amazon_Chime_SDK_Meetings.html
  AmazonChimeSdkPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AmazonChimeSdkActions
            Effect: Allow
            Action:
              - chime:CreateMeeting
              # - chime:CreateMeetingWithAttendees
              - chime:GetMeeting
              - chime:DeleteMeeting
              - chime:CreateAttendee
              - chime:ListAttendees
              - chime:GetAttendee
              - chime:DeleteAttendee
              # - chime:BatchCreateAttendee
              # - chime:BatchUpdateAttendeeCapabilitiesExcept
              # - chime:UpdateAttendeeCapabilities
              - chime:ListTagsForResource
              - chime:TagResource
              - chime:UntagResource
              # - chime:StartMeetingTranscription
              # - chime:StopMeetingTranscription
            Resource: "*"

Outputs:
  AmazonChimeSdkPolicyArn:
    Description: "The ARN of the ManagedPolicy to attatch to the task role."
    Value: !Ref AmazonChimeSdkPolicy